platform :ios, '14.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'PolyfenceExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  pod 'PolyfenceCore', :podspec => '../node_modules/polyfence-react-native/polyfence-react-native.podspec'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
