export { Polyfence } from './Polyfence';
export {
  onLocation,
  onGeofenceEvent,
  onError,
  onPerformance,
  normalizePolyfenceError,
  removeAllListeners,
} from './events';
export type {
  Zone,
  ZoneType,
  Coordinate,
  GeofenceEvent,
  GeofenceEventType,
  PolyfenceLocation,
  PolyfenceConfiguration,
  AccuracyProfile,
  UpdateStrategy,
  RuntimeStatus,
  PerformanceEventPayload,
  PolyfenceError,
  PolyfenceErrorType,
  PolyfenceDebugInfo,
  ZoneState,
  TrackingSchedule,
  SessionTelemetry,
  Subscription,
  BatteryOptimizationStatus,
} from './types';
